#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Apr 12 10:16:50 2022

@author: rubylintu
"""

import getopt, sys, os
import psutil
from multiprocessing import Process, Queue
import threading
import numpy as np
import time
import datetime
import random

def create_file(num):
    for i in range(num):
        basename = "tmp/mylogfile"
        suffix = datetime.datetime.now().strftime("%y%m%d_%H%M%S")
        filename = "_".join([basename, suffix]) # e.g. 'mylogfile_120508_171442'
        f = open(filename,'w+')
        f.write(str(np.random.rand(100,100)))
        f.close()
    return 1


def main():
    
    numFile = 1000000
    times = 10
    for i in range(int(numFile / times)):
     p = threading.Thread(target=create_file(times))
     p.start
    print("thread "+i+" done process")

main()